#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
#focaltech_ex_fun.o
obj-$(CONFIG_MSG2138_GC) += msg2138_qc.o
obj-$(CONFIG_MSG2138_SCAP_TEST) += msg2138_scap_test.o 
