obj-$(CONFIG_HUAWEI_KERNEL) += hw_tp_common.o
obj-$(CONFIG_HUAWEI_KERNEL) += getevent_common_report.o
#obj-$(CONFIG_CYTTSP5_CS445A)		+= cyttsp5_cs445a/
obj-$(CONFIG_HUAWEI_KERNEL)		+= cyttsp5_cs445a/
obj-$(CONFIG_SYNAPTICS_DSX_S3207)	+= synaptics_dsx_s3207/
