obj-$(CONFIG_HUAWEI_KERNEL) += hw_tp_common.o
obj-$(CONFIG_HUAWEI_KERNEL) += getevent_common_report.o
#obj-$(CONFIG_CYTTSP5_CS445A)		+= cyttsp5_cs445a/
obj-$(CONFIG_HUAWEI_KERNEL)		+= cyttsp5_cs445a/
obj-$(CONFIG_SYNAPTICS_DSX_S3207)	+= synaptics_dsx_s3207/
obj-$(CONFIG_GT_9XX)				+= gt9xx/
obj-$(CONFIG_FOCALTECH_6X36)		+= focaltech_6x36/
obj-$(CONFIG_MSTAR_2142)			+= mstar_2142/
