ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi
ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
