#define JL_START_BROWSER_ONCREATE_START                    "JLOG10000"
#define JL_START_BROWSER_ONCREATE_END                      "JLOG10001" 
#define JL_START_BROWSER_ACTIVITY_ONCREATE_START           "JLOG10002"
#define JL_START_BROWSER_ACTIVITY_ONCREATE_END             "JLOG10003"
#define JL_START_BROWSER_ACTIVITY_CREATE_CONTROLOR_START   "JLOG10004"
#define JL_START_BROWSER_ACTIVITY_CREATE_CONTROLOR_END     "JLOG10005"
#define JL_START_BROWSER_ACTIVITY_ONRESUME_START           "JLOG10006"
#define JL_START_BROWSER_ACTIVITY_ONRESUME_END             "JLOG10007"
#define JL_START_BROWSER_CONTROLOR_START_START             "JLOG10008"
#define JL_START_BROWSER_CONTROLOR_START_END               "JLOG10009"
#define JL_START_BROWSER_CONTROLOR_DOSTART_START           "JLOG10010"
#define JL_START_BROWSER_CONTROLOR_DOSTART_END             "JLOG10011"
#define JL_START_BROWSER_CONTROLOR_ONPRELOGIN_FINISH_START "JLOG10012"
#define JL_START_BROWSER_CONTROLOR_ONPRELOGIN_FINISH_END   "JLOG10013"
#define JL_START_BROWSER_OPEN_HOMEPAGE_START               "JLOG10014"
#define JL_START_BROWSER_OPEN_HOMEPAGE_END                 "JLOG10015"
#define JL_BROWSER_WEBVIEW_LOADURL                         "JLOG10016"
#define JL_BROWSER_WEBKIT_WEBCOREFRAMEBRIDGE_LOADURL       "JLOG10017" 
#define JL_BROWSER_WEBKIT_FRAMELOADER_LOAD                 "JLOG10018" 
#define JL_BROWSER_WEBKIT_HTMLPARSER_BEGIN                 "JLOG10019"

#define JL_BOOT_ANDROID_START_TIME                         "JLOG12001"
#define JL_DISPLAY_RENDER_EXECUTE_TRACK                    "JLOG12005"
#define JL_BOOT_ZYGOTE_PRELOAD_END_TIME                    "JLOG12008"
#define JL_BOOT_VM_CREATE_TIME                             "JLOG12009"
#define JL_BOOT_AMS_READY_TIME                             "JLOG12010"
#define JL_BOOT_AMS_START_LAUNCHER_TIME                    "JLOG12011"
#define JL_BOOT_PRIV_APP_SCAN_TIME                         "JLOG12012"
#define JL_BOOT_SYSTEM_APP_SCAN_TIME                       "JLOG12013"
#define JL_BOOT_DEL_APP_SCAN_TIME                          "JLOG12014"
#define JL_BOOT_INSTALL_APP_SCAN_TIME                      "JLOG12015"
#define JL_SENSOR_CHANGE_TIME                              "JLOG12016"
#define JL_BOOT_ACTIVITY_MANAGER_START_TIME                "JLOG12017"
#define JL_BOOT_PACKAGE_MANAGER_END_TIME                   "JLOG12018"
#define JL_BOOT_START_SERVICE_END_TIME                     "JLOG12019"
#define JL_BOOT_END_TIME                                   "JLOG12020"
#define JL_DISPLAY_COMPSITION_SLOW_NUM                     "JLOG12021"
#define JL_BOOT_SEARCH_NETWORK_CDMA_END_TIME               "JLOG12022"
#define JL_BOOT_SEARCH_NETWORK_GSM_END_TIME                "JLOG12023"
#define JL_BOOT_SEARCH_NETWORK_START_TIME                  "JLOG12024"
#define JL_DISPLAY_FRAME_BUFFER_COMMIT_SLOW_TIME           "JLOG12025"


#define JL_SURFACECONTROL_UNBLANKDISPLAY                   "JLOG14025"
#define JL_SURFACECONTROL_BLANKDISPLAY                     "JLOG14026"
#define JL_OVERSCROOL_FLING_RATE                           "JLOG14027"
#define JL_PWIND_KEYCHECKED_TOWAKEUP                       "JLOG14028"
#define JL_PWIND_KEYCHECKED_TOSLEEP                        "JLOG14029"
#define JL_CHECKED_ORIENTATION_CHANGED_START               "JLOG14030"
#define JL_PROCESSKEYEND_TIMOUT                            "JLOG14031"
#define JL_PMS_WAKEUP_START                                "JLOG14032"
#define JL_PMS_GOSLEEP_START                               "JLOG14033"
#define JL_SHUTDOWN_ENTERSHUTDOWN                          "JLOG14034"
#define JL_SHUTDOWN_ENTER_REBOOT                           "JLOG14035"
#define JL_SHUTDOWN_SEND_BROADCAST_START                   "JLOG14036"
#define JL_SHUTDOWN_ACTIVITYMANAGER_SHUTDOWN_START         "JLOG14037"
#define JL_SHUTDOWN_RADIOS_SHUTDOWN_START                  "JLOG14038"
#define JL_SHUTDOWN_MOUNTSERVICE_SHUTDOWN_START            "JLOG14039"
#define JL_SHUTDOWN_SYSTEM_SHUTDOWN_START                  "JLOG14040"
#define JL_SHUTDOWN_LOWLEVEL_SHUTDOWN_START                "JLOG14041"
#define JL_ROTATION_PROCESS_START                          "JLOG14042"
#define JL_ROTATION_CHANGED_END                            "JLOG14043"
#define JL_ROTATION_ANIMATION_COMPLETED                    "JLOG14044"
#define JL_SCREENACQUIRED_START                            "JLOG14045"
#define JL_SCREENRELEASED_START                            "JLOG14046"
#define JL_BOOT_PROGRESS_KERNEL_END                        "JLOG14047"
#define JL_POWKEY_PWIND_KEYCHECKED_TOWAKEUP                "JLOG14049"
#define JL_POWKEY_PMS_WAKEUP_START                         "JLOG14050"
#define JL_POWKEY_PWIND_KEYCHECKED_TOSLEEP                 "JLOG14051"
#define JL_POWKEY_PMS_GOSLEEP_START                        "JLOG14052"
#define JL_HWC_DISPLAY_BLANK_START                         "JLOG14053"
#define JL_HWC_DISPLAY_UNBLANK_START                       "JLOG14054"
#define JL_HWC_DISPLAY_BLANK_END                           "JLOG14055"
#define JL_HWC_DISPLAY_UNBLANK_END                         "JLOG14056"
#define JL_FRM_NOTIFY_LOCKSCREEN_ON_START                  "JLOG14057"
#define JL_FRM_LOCKSCREEN_TURNON_START                     "JLOG14058"
#define JL_FRM_LOCKSCREEN_TURNON_END                       "JLOG14059"
#define JL_FRM_SETBACKLIGHT                                "JLOG14060"
#define JL_HWC_LCD_BLANK_START                             "JLOG14061"
#define JL_HWC_LCD_BLANK_END                               "JLOG14062"
#define JL_HWC_LCD_UNBLANK_START                           "JLOG14063"
#define JL_HWC_LCD_UNBLANK_END                             "JLOG14064"
#define JL_HWC_LCD_FIRSTFRAME_START                        "JLOG14065"
#define JL_HWC_LCD_BACKLIGHT_ON                            "JLOG14066"
#define JL_HWC_LCD_BACKLIGHT_OFF                           "JLOG14067"

#define JLID_START_BROWSER_ONCREATE_START                    10000
#define JLID_START_BROWSER_ONCREATE_END                      10001 
#define JLID_START_BROWSER_ACTIVITY_ONCREATE_START           10002
#define JLID_START_BROWSER_ACTIVITY_ONCREATE_END             10003
#define JLID_START_BROWSER_ACTIVITY_CREATE_CONTROLOR_START   10004
#define JLID_START_BROWSER_ACTIVITY_CREATE_CONTROLOR_END     10005
#define JLID_START_BROWSER_ACTIVITY_ONRESUME_START           10006
#define JLID_START_BROWSER_ACTIVITY_ONRESUME_END             10007
#define JLID_START_BROWSER_CONTROLOR_START_START             10008
#define JLID_START_BROWSER_CONTROLOR_START_END               10009
#define JLID_START_BROWSER_CONTROLOR_DOSTART_START           10010
#define JLID_START_BROWSER_CONTROLOR_DOSTART_END             10011
#define JLID_START_BROWSER_CONTROLOR_ONPRELOGIN_FINISH_START 10012
#define JLID_START_BROWSER_CONTROLOR_ONPRELOGIN_FINISH_END   10013
#define JLID_START_BROWSER_OPEN_HOMEPAGE_START               10014
#define JLID_START_BROWSER_OPEN_HOMEPAGE_END                 10015
#define JLID_BROWSER_WEBVIEW_LOADURL                         10016
#define JLID_BROWSER_WEBKIT_WEBCOREFRAMEBRIDGE_LOADURL       10017 
#define JLID_BROWSER_WEBKIT_FRAMELOADER_LOAD                 10018
#define JLID_BROWSER_WEBKIT_HTMLPARSER_BEGIN                 10019

#define JLID_BOOT_ANDROID_START_TIME                         12001
#define JLID_DISPLAY_RENDER_EXECUTE_TRACK                    12005
#define JLID_BOOT_ZYGOTE_PRELOAD_END_TIME                    12008
#define JLID_BOOT_VM_CREATE_TIME                             12009
#define JLID_BOOT_AMS_READY_TIME                             12010
#define JLID_BOOT_AMS_START_LAUNCHER_TIME                    12011
#define JLID_BOOT_PRIV_APP_SCAN_TIME                         12012
#define JLID_BOOT_SYSTEM_APP_SCAN_TIME                       12013
#define JLID_BOOT_DEL_APP_SCAN_TIME                          12014
#define JLID_BOOT_INSTALL_APP_SCAN_TIME                      12015
#define JLID_SENSOR_CHANGE_TIME                              12016
#define JLID_BOOT_ACTIVITY_MANAGER_START_TIME                12017
#define JLID_BOOT_PACKAGE_MANAGER_END_TIME                   12018
#define JLID_BOOT_START_SERVICE_END_TIME                     12019
#define JLID_BOOT_END_TIME                                   12020
#define JLID_DISPLAY_COMPSITION_SLOW_NUM                     12021
#define JLID_BOOT_SEARCH_NETWORK_CDMA_END_TIME               12022
#define JLID_BOOT_SEARCH_NETWORK_GSM_END_TIME                12023
#define JLID_BOOT_SEARCH_NETWORK_START_TIME                  12024
#define JLID_DISPLAY_FRAME_BUFFER_COMMIT_SLOW_TIME           12025

#define JLID_SURFACECONTROL_UNBLANKDISPLAY                   14025
#define JLID_SURFACECONTROL_BLANKDISPLAY                     14026
#define JLID_OVERSCROOL_FLING_RATE                           14027
#define JLID_PWIND_KEYCHECKED_TOWAKEUP                       14028
#define JLID_PWIND_KEYCHECKED_TOSLEEP                        14029
#define JLID_CHECKED_ORIENTATION_CHANGED_START               14030
#define JLID_PROCESSKEYEND_TIMOUT                            14031
#define JLID_PMS_WAKEUP_START                                14032
#define JLID_PMS_GOSLEEP_START                               14033
#define JLID_SHUTDOWN_ENTERSHUTDOWN                          14034
#define JLID_SHUTDOWN_ENTER_REBOOT                           14035
#define JLID_SHUTDOWN_SEND_BROADCAST_START                   14036
#define JLID_SHUTDOWN_ACTIVITYMANAGER_SHUTDOWN_START         14037
#define JLID_SHUTDOWN_RADIOS_SHUTDOWN_START                  14038
#define JLID_SHUTDOWN_MOUNTSERVICE_SHUTDOWN_START            14039
#define JLID_SHUTDOWN_SYSTEM_SHUTDOWN_START                  14040
#define JLID_SHUTDOWN_LOWLEVEL_SHUTDOWN_START                14041
#define JLID_ROTATION_PROCESS_START                          14042
#define JLID_ROTATION_CHANGED_END                            14043
#define JLID_ROTATION_ANIMATION_COMPLETED                    14044
#define JLID_SCREENACQUIRED_START                            14045
#define JLID_SCREENRELEASED_START                            14046
#define JLID_BOOT_PROGRESS_KERNEL_END                        14047
#define JLID_POWKEY_PWIND_KEYCHECKED_TOWAKEUP                14049
#define JLID_POWKEY_PMS_WAKEUP_START                         14050
#define JLID_POWKEY_PWIND_KEYCHECKED_TOSLEEP                 14051
#define JLID_POWKEY_PMS_GOSLEEP_START                        14052
#define JLID_HWC_DISPLAY_BLANK_START                         14053
#define JLID_HWC_DISPLAY_UNBLANK_START                       14054
#define JLID_HWC_DISPLAY_BLANK_END                           14055
#define JLID_HWC_DISPLAY_UNBLANK_END                         14056
#define JLID_FRM_NOTIFY_LOCKSCREEN_ON_START                  14057
#define JLID_FRM_LOCKSCREEN_TURNON_START                     14058
#define JLID_FRM_LOCKSCREEN_TURNON_END                       14059
#define JLID_FRM_SETBACKLIGHT                                14060
#define JLID_HWC_LCD_BLANK_START                             14061
#define JLID_HWC_LCD_BLANK_END                               14062
#define JLID_HWC_LCD_UNBLANK_START                           14063
#define JLID_HWC_LCD_UNBLANK_END                             14064
#define JLID_HWC_LCD_FIRSTFRAME_START                        14065
#define JLID_HWC_LCD_BACKLIGHT_ON                            14066
#define JLID_HWC_LCD_BACKLIGHT_OFF                           14067
