ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
