ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi/sensor/cci
obj-$(CONFIG_MSMB_CAMERA_KIWI)   += msm_camera_io_util.o msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o
