ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/mini_isp
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
