ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi
ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
