#gt9xx touchpanel driver


obj-$(CONFIG_GT9XX_TOUCHPANEL_DRIVER)	+= gt9xx.o
#gt9xx update file
obj-$(CONFIG_GT9XX_TOUCHPANEL_UPDATE)	+= gt9xx_update.o
#debug tool
obj-$(CONFIG_GT9XX_TOUCHPANEL_DEBUG)	+= goodix_tool.o
#gt9xx openshort test
obj-$(CONFIG_GT9XX_TOUCHPANEL_OPENSHORT_TEST)	+= gt9xx_openshort.o

