ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi
ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi/codecs
ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi/isps
ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi/pproc
ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi/jpeg_10
ccflags-y += -Idrivers/media/platform/msm/camera_v2_kiwi/fd

obj-$(CONFIG_MSMB_CAMERA_KIWI) += msm.o
obj-$(CONFIG_MSMB_CAMERA_KIWI) += hw_camera_common.o
obj-$(CONFIG_MSMB_CAMERA_KIWI) += camera/
obj-$(CONFIG_MSMB_CAMERA_KIWI) += msm_vb2/
obj-$(CONFIG_MSMB_CAMERA_KIWI) += sensor/
obj-$(CONFIG_MSMB_CAMERA_KIWI) += pproc/
obj-$(CONFIG_MSMB_CAMERA_KIWI) += isp/
obj-$(CONFIG_MSMB_CAMERA_KIWI) += ispif/
obj-$(CONFIG_MSMB_JPEG) += jpeg_10/
obj-$(CONFIG_MSMB_CAMERA_KIWI) += msm_buf_mgr/
obj-$(CONFIG_MSMB_CAMERA_KIWI) += hw_camera_log.o

