# /*add camera ois driver*/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/ois
obj-$(CONFIG_MSMB_CAMERA) += imx278_sunny_ois.o
obj-$(CONFIG_MSMB_CAMERA) += imx278_liteon_ois.o
obj-$(CONFIG_MSMB_CAMERA) += imx278_lgit_ois.o
