ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/mini_isp
# /*add camera ois driver*/
obj-$(CONFIG_MSMB_CAMERA) += imx278_ois/
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o

obj-$(CONFIG_MSMB_CAMERA) += mini_isp_ois_interface.o
