obj-$(CONFIG_HUAWEI_ACCEL_SENSORS)			+= accelerometer/
obj-$(CONFIG_HUAWEI_COMPASS_SENSORS)		+= compass/
obj-$(CONFIG_HUAWEI_HALL_SENSORS)			+= hallsensor/
obj-$(CONFIG_HUAWEI_LP_SENSORS)				+= lpsensor/

obj-$(CONFIG_HUAWEI_SENSOR_INFO)			+= hw_sensor_info.o
obj-$(CONFIG_SENSOR_INFO)					+= sensor_info.o